# Generated by Django 3.0.5 on 2020-04-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.URLField(verbose_name='Embed Link')),
                ('year_in_school', models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'very large')], default='M', max_length=2)),
            ],
        ),
    ]
