# Generated by Django 3.0.5 on 2020-04-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='year_in_school',
            new_name='size',
        ),
    ]
