# Generated by Django 3.0.5 on 2020-04-26 23:45

import dashboard.models.panel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200426_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='embed_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='panel',
            name='size',
            field=models.CharField(choices=[(dashboard.models.panel.PanelSize['SMALL'], 'small'), (dashboard.models.panel.PanelSize['MEDIUM'], 'medium'), (dashboard.models.panel.PanelSize['LARGE'], 'large'), (dashboard.models.panel.PanelSize['VERY_LARGE'], 'very large')], default=dashboard.models.panel.PanelSize['MEDIUM'], max_length=2),
        ),
    ]
