# Generated by Django 3.0.5 on 2020-04-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200426_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='size',
            field=models.CharField(choices=[('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'very large')], default='M', max_length=2),
        ),
    ]
